unit UnitCommands;

interface

const //alpha sort ascending
  CMD_CHAT = 001;
  CMD_CHAT_START = 002;
  CMD_CHAT_STOP = 003;
  CMD_CHAT_TEXT = 004;

  CMD_CLIENT_UNINSTALL = 005;

  CMD_CLIPBOARD = 006;
  CMD_CLIPBOARD_READ = 007;
  CMD_CLIPBOARD_SET = 008;

  CMD_CONNECTION_ADD = 009;
  CMD_CONNECTION_CLOSE = 010;
  CMD_CONNECTION_RESTART = 011;

  CMD_FILESMANAGER = 012;
  CMD_FILESMANAGER_COPY = 013;
  CMD_FILESMANAGER_DELETE = 014;
  CMD_FILESMANAGER_DOWNLOAD = 015;
  CMD_FILESMANAGER_DRIVES = 016;
  CMD_FILESMANAGER_EXECUTE = 017;
  CMD_FILESMANAGER_FILES = 018;
  CMD_FILESMANAGER_FOLDERS = 019;
  CMD_FILESMANAGER_NEWFOLDER = 020;
  CMD_FILESMANAGER_RENAME = 021;
  CMD_FILESMANAGER_UPLOAD = 022;

  CMD_KEYLOGGER = 023;     
  CMD_KEYLOGGER_DELETE = 024;  
  CMD_KEYLOGGER_LOGS = 025;
  CMD_KEYLOGGER_READ = 026;
                   
  CMD_MAININFOS = 027;

  CMD_MICROPHONE = 028;
  CMD_MICROPHONE_CAPTURE = 029;
  CMD_MICROPHONE_START = 030;
  CMD_MICROPHONE_STOP = 031;

  CMD_MISCELLANEOUS = 032;
  CMD_MISCELLANEOUS_DESKTOP = 033;
  CMD_MISCELLANEOUS_DOWNLOAD = 034;
  CMD_MISCELLANEOUS_ICONS = 035;  
  CMD_MISCELLANEOUS_LOGOFF = 036;
  CMD_MISCELLANEOUS_MSG = 037;
  CMD_MISCELLANEOUS_REBOOT = 038;
  CMD_MISCELLANEOUS_SHELL = 039;   
  CMD_MISCELLANEOUS_SHUTDOWN = 040;
  CMD_MISCELLANEOUS_SPEAK = 041;
  CMD_MISCELLANEOUS_TRAY = 042;
  CMD_MISCELLANEOUS_TASKBAR = 043;
  CMD_MISCELLANEOUS_UPLOAD = 044;
  CMD_MISCELLANEOUS_WEBPAGE = 045;

  CMD_REGISTRYMANAGER = 046;
  CMD_REGISTRYMANAGER_ADD = 047;
  CMD_REGISTRYMANAGER_DELETE = 048;
  CMD_REGISTRYMANAGER_KEYS = 049;
  CMD_REGISTRYMANAGER_VALUES = 050;

  CMD_TASKSMANAGER = 051;
  CMD_TASKSMANAGER_PROCESS = 052;
  CMD_TASKSMANAGER_PROCESS_KILL = 053;
  CMD_TASKSMANAGER_SERVICES = 054;
  CMD_TASKSMANAGER_SERVICES_START = 055;
  CMD_TASKSMANAGER_SERVICES_STOP = 056;
  CMD_TASKSMANAGER_WINDOWS = 057;
  CMD_TASKSMANAGER_WINDOWS_CLOSE = 058;
  CMD_TASKSMANAGER_WINDOWS_HIDE = 059;
  CMD_TASKSMANAGER_WINDOWS_SHOW = 060;
  CMD_TASKSMANAGER_WINDOWS_TITLE = 061;

  CMD_SCREEN = 062;
  CMD_SCREEN_CAPTURE = 063;
  CMD_SCREEN_START = 064;
  CMD_SCREEN_STOP = 065;

  CMD_SHELL = 066;
  CMD_SHELL_START = 067;
  CMD_SHELL_STOP = 068;
  CMD_SHELL_TEXT = 069;

  CMD_WEBCAM = 070;
  CMD_WEBCAM_CAPTURE = 071;
  CMD_WEBCAM_DRIVERS = 072;
  CMD_WEBCAM_START = 073;
  CMD_WEBCAM_STOP = 074;

implementation

end.                  
